- pattern: abmcscholar.gov
  actions:
    - name: sleep
      params:
        seconds: 2
    - name: sleep
      params:
        seconds: 2
- pattern: google.com
  actions:
    - name: httperror
      params:
        code: 500
        status: "Timeout, Byeee"